
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author porti
 */
public class AirPa extends javax.swing.JFrame {

    public PalindromAir Air;

    /**
     * Creates new form AirPa
     */
    public AirPa() {
        initComponents();
        Air = new PalindromAir();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VENDER_Boleto = new javax.swing.JDialog();
        NombrePasajero = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnVENDER = new javax.swing.JButton();
        Cancelar_B = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        NombrePasajeroCANCELAR = new javax.swing.JTextField();
        btnCANCELAR = new javax.swing.JButton();
        MOSTRAR_PASAJEROS = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        VENDER = new javax.swing.JButton();
        CANCELAR = new javax.swing.JButton();
        MOSTRAR = new javax.swing.JButton();
        INGRESOS = new javax.swing.JButton();
        DESPACHAR = new javax.swing.JButton();
        REINICIAR = new javax.swing.JButton();
        BUSCAR = new javax.swing.JButton();

        NombrePasajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombrePasajeroActionPerformed(evt);
            }
        });

        jLabel1.setText("Ingrese Nombre");

        btnVENDER.setBackground(new java.awt.Color(0, 204, 0));
        btnVENDER.setText("VENDER");
        btnVENDER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVENDERActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout VENDER_BoletoLayout = new javax.swing.GroupLayout(VENDER_Boleto.getContentPane());
        VENDER_Boleto.getContentPane().setLayout(VENDER_BoletoLayout);
        VENDER_BoletoLayout.setHorizontalGroup(
            VENDER_BoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VENDER_BoletoLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(NombrePasajero, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, VENDER_BoletoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVENDER)
                .addGap(62, 62, 62))
        );
        VENDER_BoletoLayout.setVerticalGroup(
            VENDER_BoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(VENDER_BoletoLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(VENDER_BoletoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NombrePasajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(76, 76, 76)
                .addComponent(btnVENDER)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        jLabel2.setText("Nombre del Pasajero: ");

        btnCANCELAR.setBackground(new java.awt.Color(255, 0, 0));
        btnCANCELAR.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCANCELAR.setText("CANCELAR");
        btnCANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCANCELARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Cancelar_BLayout = new javax.swing.GroupLayout(Cancelar_B.getContentPane());
        Cancelar_B.getContentPane().setLayout(Cancelar_BLayout);
        Cancelar_BLayout.setHorizontalGroup(
            Cancelar_BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cancelar_BLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(Cancelar_BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnCANCELAR)
                    .addGroup(Cancelar_BLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NombrePasajeroCANCELAR, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        Cancelar_BLayout.setVerticalGroup(
            Cancelar_BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Cancelar_BLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(Cancelar_BLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NombrePasajeroCANCELAR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addComponent(btnCANCELAR)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout MOSTRAR_PASAJEROSLayout = new javax.swing.GroupLayout(MOSTRAR_PASAJEROS.getContentPane());
        MOSTRAR_PASAJEROS.getContentPane().setLayout(MOSTRAR_PASAJEROSLayout);
        MOSTRAR_PASAJEROSLayout.setHorizontalGroup(
            MOSTRAR_PASAJEROSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        MOSTRAR_PASAJEROSLayout.setVerticalGroup(
            MOSTRAR_PASAJEROSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        VENDER.setBackground(new java.awt.Color(0, 153, 153));
        VENDER.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        VENDER.setText("VENDER BOLETO");
        VENDER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VENDERActionPerformed(evt);
            }
        });

        CANCELAR.setBackground(new java.awt.Color(0, 153, 153));
        CANCELAR.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        CANCELAR.setText("CANCELAR BOLETO");
        CANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELARActionPerformed(evt);
            }
        });

        MOSTRAR.setBackground(new java.awt.Color(0, 153, 153));
        MOSTRAR.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        MOSTRAR.setText("MOSTRAR PASAJEROS");
        MOSTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MOSTRARActionPerformed(evt);
            }
        });

        INGRESOS.setBackground(new java.awt.Color(0, 153, 153));
        INGRESOS.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        INGRESOS.setText("INGRESOS TOTALES");
        INGRESOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                INGRESOSActionPerformed(evt);
            }
        });

        DESPACHAR.setBackground(new java.awt.Color(0, 153, 153));
        DESPACHAR.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        DESPACHAR.setText("DESPACHAR AVION");
        DESPACHAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DESPACHARActionPerformed(evt);
            }
        });

        REINICIAR.setBackground(new java.awt.Color(0, 153, 153));
        REINICIAR.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        REINICIAR.setText("REINICIAR ASIENTOS");
        REINICIAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REINICIARActionPerformed(evt);
            }
        });

        BUSCAR.setBackground(new java.awt.Color(0, 153, 153));
        BUSCAR.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        BUSCAR.setText("BUSCAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BUSCAR)
                .addGap(37, 37, 37))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CANCELAR)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(VENDER))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(DESPACHAR)
                                    .addComponent(INGRESOS))
                                .addGap(33, 33, 33)
                                .addComponent(REINICIAR))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(MOSTRAR)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BUSCAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(VENDER)
                .addGap(18, 18, 18)
                .addComponent(CANCELAR)
                .addGap(18, 18, 18)
                .addComponent(MOSTRAR)
                .addGap(18, 18, 18)
                .addComponent(INGRESOS)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DESPACHAR)
                    .addComponent(REINICIAR))
                .addGap(45, 45, 45))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VENDERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VENDERActionPerformed
        // TODO add your handling code here:
        this.VENDER_Boleto.setVisible(true);
        VENDER_Boleto.setSize(400, 300);
        VENDER_Boleto.setLocationRelativeTo(null);
    }//GEN-LAST:event_VENDERActionPerformed

    private void btnVENDERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVENDERActionPerformed
        // TODO add your handling code here:
        String nombrePasajero = NombrePasajero.getText();

         boolean ventaExitosa = Air.sellTicket(nombrePasajero);

        if (ventaExitosa) {
            // Mostrar un mensaje de éxito en la interfaz gráfica
            JOptionPane.showMessageDialog(null, "Boleto vendido con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "No se pudo vender el boleto.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnVENDERActionPerformed

    private void NombrePasajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombrePasajeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombrePasajeroActionPerformed

    private void btnCANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCANCELARActionPerformed
        String nombrePasajero = NombrePasajeroCANCELAR.getText(); // Obtener el nombre del campo de texto

        boolean boletoCancelado = Air.cancelTicket(nombrePasajero);

        if (boletoCancelado) {
            JOptionPane.showMessageDialog(null, "Boleto cancelado exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "El pasajero o boleto no fue encontrado.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnCANCELARActionPerformed

    private void CANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELARActionPerformed
        // TODO add your handling code here:
        this.Cancelar_B.setVisible(true);
        Cancelar_B.setSize(400, 300);
        Cancelar_B.setLocationRelativeTo(null);
    }//GEN-LAST:event_CANCELARActionPerformed

    private void MOSTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MOSTRARActionPerformed
         String pasajeros = Air.printPassengers();

    if (!pasajeros.isEmpty()) {
        JOptionPane.showMessageDialog(null, pasajeros, "Pasajeros", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(null, "No hay pasajeros en el avión.", "Información", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_MOSTRARActionPerformed

    private void INGRESOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_INGRESOSActionPerformed
        // TODO add your handling code here:
           double ingresos = Air.income();

        // Mostrar los ingresos totales en un cuadro de diálogo
        JOptionPane.showMessageDialog(null, "Ingresos totales: $" + ingresos, "Ingresos Totales", JOptionPane.INFORMATION_MESSAGE);
    
    }//GEN-LAST:event_INGRESOSActionPerformed

    private void REINICIARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REINICIARActionPerformed

        Air.reset();

        // Mostrar un mensaje de éxito en la interfaz gráfica
        JOptionPane.showMessageDialog(null, "Los asientos han sido reiniciados.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
    
    }//GEN-LAST:event_REINICIARActionPerformed

    private void DESPACHARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DESPACHARActionPerformed

        Air.dispatch();
        JOptionPane.showMessageDialog(null, "El avión ha sido despachado exitosamente.", "Despacho Exitoso", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_DESPACHARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AirPa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AirPa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AirPa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AirPa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AirPa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUSCAR;
    private javax.swing.JButton CANCELAR;
    private javax.swing.JDialog Cancelar_B;
    private javax.swing.JButton DESPACHAR;
    private javax.swing.JButton INGRESOS;
    private javax.swing.JButton MOSTRAR;
    private javax.swing.JDialog MOSTRAR_PASAJEROS;
    private javax.swing.JTextField NombrePasajero;
    private javax.swing.JTextField NombrePasajeroCANCELAR;
    private javax.swing.JButton REINICIAR;
    private javax.swing.JButton VENDER;
    private javax.swing.JDialog VENDER_Boleto;
    private javax.swing.JButton btnCANCELAR;
    private javax.swing.JButton btnVENDER;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
